// Generated from the Expo app's AdminCrudList screens (expo/app/admin-settings-*.tsx).
// Keys, labels and field types match the Expo panel so both edit the same rows.
// The three nested insurance subtitles were dynamic (parent names) in Expo and are fixed text here.

import 'admin_settings_models.dart';

const crudCategories = <SettingsCategory>[
  SettingsCategory(
    key: "advertisement-banners",
    page: "admin-settings-advertisement-banners",
    title: "Advertisement Banners",
    subtitle: "In-app banner ads",
    table: "settings_entries",
    primaryKey: "title",
    secondaryKey: "url",
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("title", "Title", FieldKind.text, required: true),
      SettingsField("url", "Image URL", FieldKind.text),
      SettingsField("link", "Link", FieldKind.text),
      SettingsField("active", "Active", FieldKind.boolean),
    ],
  ),
  SettingsCategory(
    key: "app-version-setting",
    page: "admin-settings-app-version",
    title: "App Version",
    subtitle: "Force update controls",
    table: "settings_entries",
    primaryKey: "platform",
    secondaryKey: "version",
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("platform", "Platform", FieldKind.text, required: true),
      SettingsField("version", "Latest Version", FieldKind.text, required: true),
      SettingsField("minVersion", "Min Version", FieldKind.text),
      SettingsField("forceUpdate", "Force Update", FieldKind.boolean),
    ],
  ),
  SettingsCategory(
    key: "ev-delivery-advisors",
    page: "admin-settings-ev-delivery-advisors",
    title: "Delivery Advisors",
    subtitle: "Assign DAs to handle EV deliveries",
    table: "ev_delivery_advisors",
    primaryKey: "name",
    secondaryKey: "dealership",
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("country", "Country", FieldKind.text, required: true),
      SettingsField("state", "State", FieldKind.text, required: true),
      SettingsField("city", "City", FieldKind.text, required: true),
      SettingsField("dealership", "Dealership Name", FieldKind.text, required: true),
      SettingsField("name", "Advisor Name", FieldKind.text, required: true),
      SettingsField("idNumber", "ID / Passport Number", FieldKind.text),
      SettingsField("contact", "Contact Number", FieldKind.text, required: true),
      SettingsField("email", "Email Address", FieldKind.text, required: true),
      SettingsField("daNumber", "DA Number", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "ev-delivery-checklist",
    page: "admin-settings-ev-delivery-checklist",
    title: "Delivery Checklist",
    subtitle: "Handover items advisors confirm with the customer",
    table: "settings_entries",
    primaryKey: "name",
    secondaryKey: "details",
    orderKey: "displayPriority",
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Checklist Item", FieldKind.text, required: true),
      SettingsField("details", "Guidance", FieldKind.text),
      SettingsField("displayPriority", "Order", FieldKind.number),
    ],
  ),
  SettingsCategory(
    key: "email-templates",
    page: "admin-settings-email-templates",
    title: "Email Templates",
    subtitle: "Manage email content",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Template Name", FieldKind.text, required: true),
      SettingsField("subject", "Subject", FieldKind.text, required: true),
      SettingsField("body", "Body", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "fixed-price",
    page: "admin-settings-fixed-price",
    title: "Fixed Price",
    subtitle: "Fixed-fare routes",
    table: "settings_entries",
    primaryKey: "from",
    secondaryKey: "to",
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("from", "From", FieldKind.text, required: true),
      SettingsField("to", "To", FieldKind.text, required: true),
      SettingsField("price", "Price", FieldKind.number, required: true),
    ],
  ),
  SettingsCategory(
    key: "free-ride",
    page: "admin-settings-free-ride",
    title: "Free Ride",
    subtitle: "Free ride campaigns",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Campaign Name", FieldKind.text, required: true),
      SettingsField("limit", "Limit per User", FieldKind.number),
      SettingsField("maxAmount", "Max Amount", FieldKind.number),
      SettingsField("active", "Active", FieldKind.boolean),
    ],
  ),
  SettingsCategory(
    key: "geo-fencing",
    page: "admin-settings-geo-fencing",
    title: "Geo Fencing",
    subtitle: "Define operating zones",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Zone Name", FieldKind.text, required: true),
      SettingsField("radius", "Radius (km)", FieldKind.number, required: true),
      SettingsField("centerLat", "Center Lat", FieldKind.number),
      SettingsField("centerLng", "Center Lng", FieldKind.number),
    ],
  ),
  SettingsCategory(
    key: "insurance-providers",
    page: "admin-settings-insurance-providers",
    title: "Insurance Providers",
    subtitle: "Tap a provider to manage its insurance types",
    table: "insurance_providers",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: "insurance-types",
    childScopeKey: "providerId",
    nested: false,
    fields: [
      SettingsField("name", "Provider Name", FieldKind.text, required: true),
      SettingsField("type", "Category (General / Life / Takaful)", FieldKind.text),
      SettingsField("contact", "Contact", FieldKind.text),
      SettingsField("website", "Website", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "insurance-types",
    page: "admin-settings-insurance-types",
    title: "Insurance Types",
    subtitle: "Cover types offered by this provider",
    table: "insurance_types",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: "insurance-durations",
    childScopeKey: "typeId",
    nested: true,
    fields: [
      SettingsField("name", "Insurance Type Name", FieldKind.text, required: true),
      SettingsField("description", "Description", FieldKind.text),
      SettingsField("coverage", "Coverage Summary", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "leaderboard",
    page: "admin-settings-leaderboard",
    title: "Leaderboard",
    subtitle: "Top partner rankings",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Tier Name", FieldKind.text, required: true),
      SettingsField("minRides", "Min Rides", FieldKind.number),
      SettingsField("prize", "Prize", FieldKind.number),
    ],
  ),
  SettingsCategory(
    key: "page-list",
    page: "admin-settings-page-list",
    title: "Page List",
    subtitle: "Static content pages",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Page Name", FieldKind.text, required: true),
      SettingsField("slug", "Slug", FieldKind.text, required: true),
      SettingsField("content", "Content", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "driver-incentive",
    page: "admin-settings-driver-incentive",
    title: "Partner Incentive",
    subtitle: "Bonus & incentive rules",
    table: "driver_incentive",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Name", FieldKind.text, required: true),
      SettingsField("minRides", "Minimum Rides", FieldKind.number),
      SettingsField("reward", "Reward", FieldKind.number, required: true),
      SettingsField("active", "Active", FieldKind.boolean),
    ],
  ),
  SettingsCategory(
    key: "insurance-durations",
    page: "admin-settings-insurance-durations",
    title: "Premium Durations",
    subtitle: "Premium durations for this cover type",
    table: "insurance_durations",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: "insurance-premium",
    childScopeKey: "durationId",
    nested: true,
    fields: [
      SettingsField("name", "Duration Name", FieldKind.text, required: true),
      SettingsField("unit", "Unit (hour / day / week / month / year)", FieldKind.text),
      SettingsField("quantity", "Quantity per cycle", FieldKind.number),
    ],
  ),
  SettingsCategory(
    key: "insurance-premium",
    page: "admin-settings-insurance-premium",
    title: "Premium Plans",
    subtitle: "Premium plans for this duration",
    table: "insurance_premium",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: true,
    fields: [
      SettingsField("name", "Plan Name", FieldKind.text, required: true),
      SettingsField("cost", "Premium Cost", FieldKind.number, required: true),
      SettingsField("currency", "Currency (e.g. MYR)", FieldKind.text),
      SettingsField("startCalc", "Start Time Calculation", FieldKind.text),
      SettingsField("endCalc", "End Time Calculation", FieldKind.text),
      SettingsField("notes", "Notes", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "promocode-list",
    page: "admin-settings-promocode",
    title: "Promocode",
    subtitle: "Promo code campaigns",
    table: "settings_entries",
    primaryKey: "code",
    secondaryKey: "description",
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("code", "Code", FieldKind.text, required: true),
      SettingsField("description", "Description", FieldKind.text),
      SettingsField("discount", "Discount", FieldKind.number, required: true),
      SettingsField("maxUses", "Max Uses", FieldKind.number),
      SettingsField("active", "Active", FieldKind.boolean),
    ],
  ),
  SettingsCategory(
    key: "referral-settings",
    page: "admin-settings-referral",
    title: "Referral Settings",
    subtitle: "Configure referral rewards",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Name", FieldKind.text, required: true),
      SettingsField("reward", "Reward Amount", FieldKind.number, required: true),
      SettingsField("type", "Type", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "referral-tree",
    page: "admin-settings-referral-tree",
    title: "Referral Tree",
    subtitle: "Multi-level rewards",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Level Name", FieldKind.text, required: true),
      SettingsField("percentage", "Percentage %", FieldKind.number, required: true),
    ],
  ),
  SettingsCategory(
    key: "rides",
    page: "admin-settings-rides",
    title: "Rides",
    subtitle: "Ride configuration",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Setting Name", FieldKind.text, required: true),
      SettingsField("value", "Value", FieldKind.number, required: true),
      SettingsField("unit", "Unit", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "search-radius",
    page: "admin-settings-search-radius",
    title: "Search Radius",
    subtitle: "Partner search range",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Tier Name", FieldKind.text, required: true),
      SettingsField("radius", "Radius (km)", FieldKind.number, required: true),
    ],
  ),
  SettingsCategory(
    key: "social-links",
    page: "admin-settings-social-links",
    title: "Social Links",
    subtitle: "Manage social profiles",
    table: "settings_entries",
    primaryKey: "platform",
    secondaryKey: "url",
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("platform", "Platform", FieldKind.text, required: true),
      SettingsField("url", "URL", FieldKind.text, required: true),
    ],
  ),
  SettingsCategory(
    key: "subscription-plan",
    page: "admin-settings-subscription-plan",
    title: "Subscription Plan",
    subtitle: "Partner subscription tiers",
    table: "settings_entries",
    primaryKey: null,
    secondaryKey: null,
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("name", "Plan Name", FieldKind.text, required: true),
      SettingsField("price", "Price", FieldKind.number, required: true),
      SettingsField("duration", "Duration (days)", FieldKind.number),
      SettingsField("features", "Features", FieldKind.text),
    ],
  ),
  SettingsCategory(
    key: "world-currency",
    page: "admin-settings-world-currency",
    title: "World Currency",
    subtitle: "Supported currencies",
    table: "settings_entries",
    primaryKey: "code",
    secondaryKey: "symbol",
    orderKey: null,
    childCategory: null,
    childScopeKey: null,
    nested: false,
    fields: [
      SettingsField("code", "Currency Code", FieldKind.text, required: true),
      SettingsField("symbol", "Symbol", FieldKind.text, required: true),
      SettingsField("rate", "Exchange Rate", FieldKind.number),
    ],
  ),
];
