// Generates the help assistant's two copies of its knowledge base from
// assets/help/help_articles.json, so they cannot drift apart:
//
//   * lib/src/core/help_kb.dart — the articles as a const list, ranked on the
//     device when the `help_search` RPC cannot be reached;
//   * the seed block of supabase/migrations/0130_help_articles.sql.
//
//     dart run scripts/gen_help_kb.dart
//
// test/help_kb_test.dart fails when either is out of date.
import 'dart:convert';
import 'dart:io';

const _json = 'assets/help/help_articles.json';
const _dart = 'lib/src/core/help_kb.dart';
const _migration = 'supabase/migrations/0130_help_articles.sql';
const _begin = '-- BEGIN help_articles seed';
const _end = '-- END help_articles seed';

String _dartString(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$').replaceAll('\n', r'\n')}'";

String _dartList(List<dynamic> l) => '[${l.map((e) => _dartString(e as String)).join(', ')}]';

String _sql(String? s) => s == null ? 'null' : "'${s.replaceAll("'", "''")}'";

String _sqlArray(List<dynamic> l) =>
    l.isEmpty ? "'{}'::text[]" : 'array[${l.map((e) => _sql(e as String)).join(', ')}]::text[]';

void main() {
  final articles = (jsonDecode(File(_json).readAsStringSync()) as List).cast<Map<String, dynamic>>();

  final dart = StringBuffer()
    ..writeln('// GENERATED by scripts/gen_help_kb.dart from assets/help/help_articles.json.')
    ..writeln('// Do not edit by hand: edit the JSON and run `dart run scripts/gen_help_kb.dart`.')
    ..writeln()
    ..writeln("import 'help_article.dart';")
    ..writeln()
    ..writeln('/// The built-in help articles, for answering offline (the same rows')
    ..writeln('/// migration 0130 seeds into `help_articles`).')
    ..writeln('const helpKnowledgeBase = <HelpArticle>[');
  for (final a in articles) {
    dart
      ..writeln('  HelpArticle(')
      ..writeln('    id: ${_dartString(a['id'] as String)},')
      ..writeln('    title: ${_dartString(a['title'] as String)},')
      ..writeln('    questionVariants: ${_dartList(a['question_variants'] as List)},')
      ..writeln('    answer: ${_dartString(a['answer'] as String)},')
      ..writeln('    keywords: ${_dartList(a['keywords'] as List)},')
      ..writeln('    audience: ${_dartString(a['audience'] as String)},')
      ..writeln('    category: ${_dartString(a['category'] as String)},');
    if (a['action_label'] != null) dart.writeln('    actionLabel: ${_dartString(a['action_label'] as String)},');
    if (a['action_route'] != null) dart.writeln('    actionRoute: ${_dartString(a['action_route'] as String)},');
    dart
      ..writeln('    sort: ${a['sort']},')
      ..writeln('  ),');
  }
  dart.writeln('];');
  File(_dart).writeAsStringSync(dart.toString());
  Process.runSync('dart', ['format', '-l', '120', _dart]);

  final seed = StringBuffer()
    ..writeln(_begin)
    ..writeln('insert into public.help_articles')
    ..writeln(
      '  (id, title, question_variants, answer, keywords, audience, category, action_label, action_route, sort)',
    )
    ..writeln('values');
  for (var i = 0; i < articles.length; i++) {
    final a = articles[i];
    seed
      ..writeln("  ('${a['id']}', ${_sql(a['title'] as String)},")
      ..writeln('   ${_sqlArray(a['question_variants'] as List)},')
      ..writeln('   ${_sql(a['answer'] as String)},')
      ..writeln('   ${_sqlArray(a['keywords'] as List)},')
      ..writeln(
        '   ${_sql(a['audience'] as String)}, ${_sql(a['category'] as String)}, '
        '${_sql(a['action_label'] as String?)}, ${_sql(a['action_route'] as String?)}, ${a['sort']})'
        '${i == articles.length - 1 ? '' : ','}',
      );
  }
  seed
    ..writeln('on conflict (id) do nothing;')
    ..write(_end);
  final sql = File(_migration).readAsStringSync();
  final start = sql.indexOf(_begin), stop = sql.indexOf(_end);
  if (start < 0 || stop < start) throw StateError('$_migration has no seed markers');
  File(_migration).writeAsStringSync(sql.replaceRange(start, stop + _end.length, seed.toString()));
  stdout.writeln('${articles.length} articles → $_dart, $_migration');
}
